### PR TITLE
Added ru_ru.json

### PR DESCRIPTION
**Pull request by Felix14-v2**
Just a localization into my native language :3
ModMenu description also has been translated.

### CODE REVIEW

**Comment by KingContaria** [comment]
Awesome! :D
could you tell me roughly what the shortened summary says in english so i can add one for english too thats similar?

**Comment by Felix14-v2** [comment]
> shortened summary says in english

The "raw" translation is `Get back to the title screen faster! World will be saved later.` 
I had to take into account the limited space for the summary — at the maximum scale of the UI, there is not much of it. So, I had to shorten the phrase.

**Comment by KingContaria** [comment]
@Felix14-v2 also there is two new translations if you want to take a look :)

**Comment by Felix14-v2** [comment]
> is there a reason to use "worldname" instead of 'worldname'?

Yep, just a local rule in Russian, we don't use apostrophe at all ¯\_(◕‿◕)_/¯

>  is an edge case where multiple worlds are saving

As for this, I tried to reproduce this scenario ingame to check the translation correctness, but in my case Minecraft just froze. If you have a screenshot, could you let me take a look?

> there is two new translations if you want to take a look :)

Sure, I try to keep my translations up-to-date, but it's not always possible to do it quickly. I have limited access to my PC, so there is a delay.

**Comment by KingContaria** [comment]
> Yep, just a local rule in Russian, we don't use apostrophe at all ¯\_(◕‿◕)_/¯

Hm okay in that case i'll just change it in english, since using "" is i think correct everywhere :)
> As for this, I tried to reproduce this scenario ingame to check the translation correctness, but in my case Minecraft just froze. If you have a screenshot, could you let me take a look?

I was also only able to do this by changing some code lol, otherwise they were saving too fast to have 2 at the same time. it just adds `' & '` between the world names (i will change it to `" & "` to make it correct in russian)

> Sure, I try to keep my translations up-to-date, but it's not always possible to do it quickly. I have limited access to my PC, so there is a delay.

Of course, take your time! It's really awesome that you contributed the translations i really appreciate it :D

**Pull request merged**
