### PR TITLE
1.20.4

### PR DESCRIPTION
**Pull request by Madis0**
- Updated dependencies to 1.20.4
- Removed MixinExtras as it is provided by Loader 0.15.0
- 5 mixin errors fixed by Clonclem

### CODE REVIEW

**Comment by Clomclem** [comment]
I've fixed those issues, how do I add to the pull?

**Comment by KingContaria** [comment]
Hey, thanks for the mixin work.
I'm on vacation and won't be back til next year.
Glancing over the changes on my phone there is some stuff I'm not happy with, since i don't know how to make a review on my phone tho im gonna make a list here:

IntegratedServerLoaderMixin - removing the setscreen is not good, instead we probably want to replace it with running the onCancel runnable (idk how vanilla does it exactly)

LevelStorageSessionMixin - simply removing the methods is not good, we are synchronizing them using our Synchronized annotation, instead wed want to find their equivalents in the new code and synchronize those
also do we need to specify the parameters for save in the inject?

MinecraftClientMixin - is that change even needed? unless they added a second method named printCrashreport it doesnt seem like it would. what i assume happened here is that they changed some parameters, so the current version doesnt work, however we dont need to change anything for that, just recompile against the new version

**Comment by Clomclem** [comment]
Thanks for the feedback!

For the first one, I need to investigate how it works, since now vanilla creates different instances of different screens in case of error, I’ll look into it.

For the second one, I’ll also look into it, idk if it’s a rename or if it was simply removed, but I’ll try to fix it.

For the third, there are now 3 printCrashReport methods, and the first two of them are just wrappers for the third, which is why I changed the Inject to that one.

**Comment by KingContaria** [comment]
for number 3, that makes sense, you could still remove the parameters from the handler method since we dont use them, as long as its in the signature its fine

**Comment by KingContaria** [comment]
Hi, I'm gonna be available to work on the update this week, if you don't mind I'll merge this pr in the coming days and sort out the remaining issues

**Comment by KingContaria** [comment]
alright, merged, i will make the additional fixes either today or tomorrow

**Comment by KingContaria** [comment]
thanks for the pr! :)

**Pull request merged**
