### PR TITLE
Add german translation

### PR DESCRIPTION
**Pull request by JustAlittleWolf**

### CODE REVIEW

**Review by KingContaria — CHANGES_REQUESTED** [review]
could you edit the toast.fastquit.description to integrate \"%s\" correctly?
it will be replaced by the saving world's name, which would currently look like this:
`Speichern abgeschlossen"Lorem ipsum"`

**Comment by KingContaria** [comment]
oh and it would be cool if in `options.fastquit.renderSavingScreen` the Text in would represent the german translation of the screen ingame (\"Welt wird gespeichert\")

**Comment by JustAlittleWolf** [comment]
Thanks for the correction, should be fine now.

**Review by KingContaria — APPROVED** [review]
lgtm!

**Comment by KingContaria** [comment]
will merge, thank you for the contribution! :)

**Pull request merged**
